### ISSUE TITLE
[Feature] 이미지 만들어서 동작하게끔 하기

### ISSUE THREAD

**Issue by seokunee** [seokunee/Inception#1]
## 📃 Description

기본적으로 nginx, wordpress, mariadb가 docker network에서 동작하도록 필요 문서들을 작성한다.

## ☑ Todo
- [ ] docker-compose.yml 파일 작성
- [x] #3
- [ ] wordpress Dockerfile 작성
- [ ] mariadb Dockerfile 작성
